---
- name: Explore multi-host variables
  hosts: linux
  gather_facts: true
  

  tasks:
    - name: Show server information
      ansible.builtin.debug:
        msg: "{{ application_name }} - {{ ansible_facts['hostname'] }} - {{ server_role }}" 
    
    - name: Show total memory
      ansible.builtin.debug:
        msg: "Server {{ ansible_facts['hostname'] }} has {{ ansible_facts['memtotal_mb'] }} MB of RAM"

      
