---
- name: Configure Nginx web server
  hosts: linux 
  become: true

  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx 
        state: present
        update_cache: true

    - name: Ensure Nginx is enable and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

      