---
- name: Configure Nginx web server
  hosts: linux 
  become: true

  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx 
        state: present
        update_cache: true

    - name: Ensure Nginx is enable and running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    
    - name: Deploy Olympus web page
      ansible.builtin.template:
        src: ../templates/index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      
